# Generated by Django 2.1.2 on 2019-08-06 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 13, 35, 34, 409657)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 13, 35, 34, 409679)),
        ),
    ]
