# Generated by Django 2.1.2 on 2019-08-06 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20190806_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 13, 41, 42, 770103)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 13, 41, 42, 770122)),
        ),
    ]
