# Generated by Django 2.1.2 on 2019-08-06 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_auto_20190806_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 6, 13, 51, 52, 998656)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 6, 13, 51, 52, 998675)),
        ),
    ]
