# Generated by Django 2.1.2 on 2019-08-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0010_auto_20190806_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.IntegerField(),
        ),
    ]
