# Generated by Django 2.1.2 on 2019-08-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0016_auto_20190806_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayname',
            name='day_name',
        ),
        migrations.AlterField(
            model_name='dayname',
            name='order',
            field=models.IntegerField(choices=[(0, 'poniedziałek'), (1, 'wtorek'), (2, 'środa'), (3, 'czwartek'), (4, 'piątek'), (5, 'sobota'), (6, 'niedziela')]),
        ),
    ]
