# Generated by Django 2.1.2 on 2019-08-06 12:58

from django.db import migrations, models
import jedzonko.models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0017_auto_20190806_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(default=jedzonko.models.Page.slug, max_length=255, unique=True),
        ),
    ]
