# Generated by Django 2.1.2 on 2019-08-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0018_auto_20190806_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255), max_length=40),
        ),
    ]
