# Generated by Django 2.1.2 on 2019-08-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0020_auto_20190806_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
