# Generated by Django 2.1.2 on 2019-08-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0021_auto_20190809_0817'),
        ('jedzonko', '0021_auto_20190808_1303'),
    ]

    operations = [
    ]
