# Generated by Django 2.1.2 on 2019-08-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0021_auto_20190809_1734'),
        ('jedzonko', '0022_merge_20190809_0931'),
    ]

    operations = [
    ]
