# Generated by Django 2.1.2 on 2019-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0023_merge_20190813_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_recipe',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
